/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MaasRouteImport } from './routes/maas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HaklarimRouteImport } from './routes/haklarim'
import { Route as GelisimRouteImport } from './routes/gelisim'
import { Route as AsistanRouteImport } from './routes/asistan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SektorSectorIdRouteImport } from './routes/sektor.$sectorId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MaasRoute = MaasRouteImport.update({
  id: '/maas',
  path: '/maas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HaklarimRoute = HaklarimRouteImport.update({
  id: '/haklarim',
  path: '/haklarim',
  getParentRoute: () => rootRouteImport,
} as any)
const GelisimRoute = GelisimRouteImport.update({
  id: '/gelisim',
  path: '/gelisim',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistanRoute = AsistanRouteImport.update({
  id: '/asistan',
  path: '/asistan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorSectorIdRoute = SektorSectorIdRouteImport.update({
  id: '/sektor/$sectorId',
  path: '/sektor/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistan': typeof AsistanRoute
  '/gelisim': typeof GelisimRoute
  '/haklarim': typeof HaklarimRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/maas': typeof MaasRoute
  '/otp': typeof OtpRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sektor/$sectorId': typeof SektorSectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistan': typeof AsistanRoute
  '/gelisim': typeof GelisimRoute
  '/haklarim': typeof HaklarimRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/maas': typeof MaasRoute
  '/otp': typeof OtpRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sektor/$sectorId': typeof SektorSectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistan': typeof AsistanRoute
  '/gelisim': typeof GelisimRoute
  '/haklarim': typeof HaklarimRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/maas': typeof MaasRoute
  '/otp': typeof OtpRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sektor/$sectorId': typeof SektorSectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistan'
    | '/gelisim'
    | '/haklarim'
    | '/home'
    | '/login'
    | '/maas'
    | '/otp'
    | '/profil'
    | '/sitemap.xml'
    | '/sektor/$sectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistan'
    | '/gelisim'
    | '/haklarim'
    | '/home'
    | '/login'
    | '/maas'
    | '/otp'
    | '/profil'
    | '/sitemap.xml'
    | '/sektor/$sectorId'
  id:
    | '__root__'
    | '/'
    | '/asistan'
    | '/gelisim'
    | '/haklarim'
    | '/home'
    | '/login'
    | '/maas'
    | '/otp'
    | '/profil'
    | '/sitemap.xml'
    | '/sektor/$sectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistanRoute: typeof AsistanRoute
  GelisimRoute: typeof GelisimRoute
  HaklarimRoute: typeof HaklarimRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MaasRoute: typeof MaasRoute
  OtpRoute: typeof OtpRoute
  ProfilRoute: typeof ProfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SektorSectorIdRoute: typeof SektorSectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maas': {
      id: '/maas'
      path: '/maas'
      fullPath: '/maas'
      preLoaderRoute: typeof MaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haklarim': {
      id: '/haklarim'
      path: '/haklarim'
      fullPath: '/haklarim'
      preLoaderRoute: typeof HaklarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gelisim': {
      id: '/gelisim'
      path: '/gelisim'
      fullPath: '/gelisim'
      preLoaderRoute: typeof GelisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistan': {
      id: '/asistan'
      path: '/asistan'
      fullPath: '/asistan'
      preLoaderRoute: typeof AsistanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektor/$sectorId': {
      id: '/sektor/$sectorId'
      path: '/sektor/$sectorId'
      fullPath: '/sektor/$sectorId'
      preLoaderRoute: typeof SektorSectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistanRoute: AsistanRoute,
  GelisimRoute: GelisimRoute,
  HaklarimRoute: HaklarimRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MaasRoute: MaasRoute,
  OtpRoute: OtpRoute,
  ProfilRoute: ProfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SektorSectorIdRoute: SektorSectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
